language: r

services:
  - docker

before_install:
  - docker pull thomaschln/snpclust
  - docker run thomaschln/snpclust

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
