# from Rcpp

os: linux
dist: trusty
services: docker

env:
  global:
    - DOCKER_OPTS="--rm -w /snpclust"
      DOCKER_CNTR="thomaschln/snpclust"

install:
  - docker pull ${DOCKER_CNTR}

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} make check

after_success:
  - docker run ${DOCKER_OPTS} -e CODECOV_TOKEN ${DOCKER_CNTR} ./codecov.sh
