language: r

services:
  - docker

install:
  - docker pull thomaschln/snpclust

script:
  - docker run -w /snpclust thomaschln/snpclust make check

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
