services:
  - docker

install:
  - docker pull thomaschln/snpclust

script:
  - docker run -w /snpclust thomaschln/snpclust make check

after_success:
  - docker run  -w /snpclust thomaschln/snpclust R -e "install.packages('covr'); covr::codecov()"
